apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: k8s-sample-gke-about
    newName: jchengdeveng/k8s-sample-gke-about
    newTag: "${IMAGE_TAG}"
