import type { ComponentStoryFn, ComponentMeta } from '@storybook/react';
import CssBaseline from '@mui/material/CssBaseline';
import { Global } from '@emotion/react';

import DraggableColorList from '.';

import seeds from '@/common/_seeds';

export default {
  title: 'Components/DraggableColorList',
  component: DraggableColorList,
  argTypes: {
    onRemoveColor: { action: 'REMOVE COLOR' },
    onSortEnd: { action: 'SORT END' },
  },
} as ComponentMeta<typeof DraggableColorList>;

const Template: ComponentStoryFn<typeof DraggableColorList> = args => (
  <div style={{ height: '100vh', width: '100vw' }}>
    <CssBaseline />
    <Global
      styles={{
        'body div': {
          lineHeight: '0', // overrides default line-height: 1.5 generated by <CssBaseline />
        },
      }}
    />
    <DraggableColorList
      {...args}
      axis="xy"
      distance={20} // workaround for DeleteIcon issue
    />
  </div>
);

export const Primary = Template.bind({});
Primary.args = {
  colors: seeds[0]?.colors,
};
