apiVersion: v1
kind: Service
metadata:
  labels:
    app: ci-cd-app
  name: ci-cd-app
spec:
  selector:
    app: ci-cd-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  type: ClusterIP
