FROM nginx:1.20.1-alpine as prod

ARG BUILD_DATE=not-set 
ARG SOURCE_COMMIT=not-set 
LABEL org.opencontainers.image.authors=jcheng.deveng@gmail.com
LABEL org.opencontainers.image.created=$BUILD_DATE 
LABEL org.opencontainers.image.revision=$SOURCE_COMMIT 
LABEL org.opencontainers.image.title="Storybook of NextJS app components in K8s cluster" 
LABEL org.opencontainers.image.licenses=MIT 
EXPOSE 80

COPY ./storybook-static/ /usr/share/nginx/html

RUN sed -i "s~</head><body>~<meta name='gitlab-tac-tac-string' content='$SOURCE_COMMIT' /></head><body>~g" /usr/share/nginx/html/index.html
