version: '3.8'
services:
  nextjs-app-dev:
    container_name: 'ci-cd-app-dev'
    image: 'ci-cd-app:dev'
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        BUILD_DATE: '$BUILD_DATE' # SSR-only
        SOURCE_COMMIT: '$COMMIT' # SSR-only
        NEXT_PORT: '${INT_PORT:-3000}' # SSR-only
        NEXT_PUBLIC_SOMEENVVAR: 'an_environment_variable_exposed_to_client_browser'
        # NEXT_PUBLIC_SOMEBACKEND_URI: '$SOMEBACKEND_URI'
    volumes:
      - .:/node
    # env_file:
    #   - ./.env
    ports:
      - '${EXT_PORT:-3000}:${INT_PORT:-3000}/tcp'
    stdin_open: true
    tty: true
  storybook:
    container_name: 'ci-cd-app-storybook'
    image: 'npm-util'
    volumes:
      - .:/app
    # env_file:
    #   - ./.env
    ports:
      - '${EXT_PORT:-6006}:${INT_PORT:-6006}/tcp'
    stdin_open: true
    tty: true
    command: run storybook
