apiVersion: v1
kind: Service
metadata:
  labels:
    app: about-cluster
  name: about-cluster
spec:
  selector:
    app: about-cluster
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
