import type { ComponentStoryFn, ComponentMeta } from '@storybook/react';
import CssBaseline from '@mui/material/CssBaseline';
import { Global } from '@emotion/react';

import MiniPalette from '.';

import seeds from '@/common/_seeds';

export default {
  title: 'Components/MiniPalette',
  component: MiniPalette,
  argTypes: {
    goToPalette: { action: 'GO TO PALETTE' },
    openDialog: { action: 'OPEN DIALOG' },
  },
  parameters: {
    layout: 'centered',
  },
} as ComponentMeta<typeof MiniPalette>;

const Template: ComponentStoryFn<typeof MiniPalette> = args => (
  <div style={{ height: '100px', width: '300px' }}>
    <CssBaseline />
    <Global
      styles={{
        'body div': {
          lineHeight: '0', // overrides default line-height: 1.5 generated by <CssBaseline />
        },
      }}
    />
    <MiniPalette {...args} />
  </div>
);

export const Primary = Template.bind({});
Primary.args = {
  // goToPalette: (id: string) => {
  //   action(`GO TO PALETTE: ${id}`);
  // },
  // openDialog: (id: string) => {
  //   action(`OPEN DIALOG: ${id}`);
  // },
  paletteName: 'Palette Name',
  id: 'palette-name',
  emoji: ':)',
  colors: seeds[0]?.colors,
};
