import type { ComponentStoryFn, ComponentMeta } from '@storybook/react';
import CssBaseline from '@mui/material/CssBaseline';
import { Global } from '@emotion/react';

import DraggableColorBox from '.';

export default {
  title: 'Components/DraggableColorBox',
  component: DraggableColorBox,
  argTypes: {
    handleDelete: { action: 'HANDLE DELETE' },
  },
} as ComponentMeta<typeof DraggableColorBox>;

const Template: ComponentStoryFn<typeof DraggableColorBox> = args => (
  <div style={{ height: '100vh', width: '100vw' }}>
    <CssBaseline />
    <Global
      styles={{
        'body div': {
          lineHeight: '0', // overrides default line-height: 1.5 generated by <CssBaseline />
        },
      }}
    />
    <DraggableColorBox {...args} />
  </div>
);

export const Primary = Template.bind({});
Primary.args = {
  color: 'gold',
  name: 'Gold',
};
